app = 'nitter'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  image = 'ghcr.io/sekai-soft/nitter-self-contained:latest'

[[mounts]]
  source = 'nitter'
  destination = '/nitter-data'
  initial_size = '1gb'

[env]
  NITTER_ACCOUNTS_FILE = "/nitter-data/guest_accounts.json"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/logo.png"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
